### ISSUE TITLE
Missing _winreg

### ISSUE THREAD

**Issue by TravisEvashkevich** [robertjoosten/maya-pip#3]
Just pip installed, but when I try to use it I get 

`PS C:\WINDOWS\system32> mayapip -h
Traceback (most recent call last):
  File "E:\Users\travis.evashkevich\AppData\Local\Programs\Python\Python35\Scripts\mayapip-script.py", line 11, in <module>
    load_entry_point('mayapip==0.1.1', 'console_scripts', 'mayapip')()

  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()

  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()

  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\mayapip\_internal\__init__.py", line 10, in <module>

    from mayapip._internal import maya
  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\mayapip\_internal\maya\__init__.py", line 9, in <module>

    from .maya_windows import get_python_executables
  File "e:\users\travis.evashkevich\appdata\local\programs\python\python35\lib\site-packages\mayapip\_internal\maya\maya_windows.py", line 2, in <module>

    import _winreg
ImportError: No module named '_winreg'`

I'm under the assumption is because this laptop has 3.5 installed where I think maya uses 2.7 right?

If that's just the case then I'll not worry about it too much for now (will be on my regular machine again soon) Close if it's just that :)

**Comment by robertjoosten** [comment]
Hello Travis,

You are right, currently the package only works in python2. It is not just winreg that is the problem, the internals if pip work a little bit different as well. I currently don't have to much time, but might figure out how to make a separate python3 version, future proofing for when Maya updates to python3 as well.
